# Generated by Django 5.0.6 on 2026-05-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('teacher', "O'qituvchi"), ('student', "O'quvchi"), ('developer', 'Dasturchi')], default='student', max_length=10, verbose_name='Rol'),
        ),
    ]
