# Generated by Django 5.0.6 on 2026-05-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_developer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('teacher', "O'qituvchi"), ('student', "O'quvchi"), ('developer', 'Dasturchi'), ('parent', 'Ota-ona')], default='student', max_length=10, verbose_name='Rol'),
        ),
    ]
