# Generated by Django 5.0.6 on 2026-08-13 11:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0005_alter_student_parent_phone_alter_student_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_at_request', models.PositiveIntegerField(verbose_name="So'rov paytidagi narx")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan / Berildi'), ('rejected', 'Rad etildi')], db_index=True, default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=300, verbose_name='Rad etish sababi')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_decisions', to=settings.AUTH_USER_MODEL, verbose_name='Kim hal qildi')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_purchases', to='students.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': "Xarid so'rovi",
                'verbose_name_plural': "Xarid so'rovlari",
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='KumushTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(verbose_name='Miqdor (+/-)')),
                ('type', models.CharField(choices=[('spend', 'Sarflandi'), ('earn', "Qo'shildi")], db_index=True, max_length=10)),
                ('reason', models.CharField(max_length=200, verbose_name='Sabab')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kumush_transactions', to='students.student', verbose_name="O'quvchi")),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='store.purchaserequest', verbose_name='Xarid')),
            ],
            options={
                'verbose_name': 'Kumush tranzaksiyasi',
                'verbose_name_plural': 'Kumush tranzaksiyalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='store/items/', verbose_name='Rasm')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Narxi (Kumush)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Qoldiq')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_store_items', to=settings.AUTH_USER_MODEL, verbose_name="Kim qo'shdi")),
            ],
            options={
                'verbose_name': "Do'kon buyumi",
                'verbose_name_plural': "Do'kon buyumlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='store.storeitem', verbose_name='Buyum'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['student', 'status'], name='store_purch_student_a50211_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['status', '-requested_at'], name='store_purch_status_2ca8c1_idx'),
        ),
    ]
