# Generated by Django 5.0.6 on 2026-08-13 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('students', '0005_alter_student_parent_phone_alter_student_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kumushtransaction',
            name='balance_after',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Keyingi balans'),
        ),
        migrations.AddField(
            model_name='kumushtransaction',
            name='balance_before',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Oldingi balans'),
        ),
        migrations.AddField(
            model_name='kumushtransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kumush_transactions_created', to=settings.AUTH_USER_MODEL, verbose_name='Kim amalga oshirdi'),
        ),
        migrations.AddField(
            model_name='kumushtransaction',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Manba ID'),
        ),
        migrations.AddField(
            model_name='kumushtransaction',
            name='source_type',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Manba turi'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='refund_reason',
            field=models.CharField(blank=True, max_length=300, verbose_name='Qaytarish sababi'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='refunded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_refunds', to=settings.AUTH_USER_MODEL, verbose_name='Kim qaytardi'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan / Berildi'), ('rejected', 'Rad etildi'), ('cancelled', 'Bekor qilindi'), ('refunded', 'Qaytarildi')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddIndex(
            model_name='kumushtransaction',
            index=models.Index(fields=['source_type', 'source_id'], name='store_kumus_source__1d4c76_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('student', 'item'), name='unique_pending_request_per_student_item'),
        ),
    ]
