# Generated by Django 5.0.6 on 2026-08-11 10:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0003_group_blank_true'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Mulk nomi')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Kategoriya')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Miqdor')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Sotib olingan sana')),
                ('purchase_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Narxi (dona)')),
                ('condition', models.CharField(choices=[('new', 'Yangi'), ('good', 'Yaxshi'), ('needs_repair', "Ta'mir talab qiladi"), ('damaged', 'Shikastlangan'), ('disposed', 'Chiqarib tashlangan')], db_index=True, default='new', max_length=15, verbose_name='Holati')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL, verbose_name="Kim qo'shdi")),
            ],
            options={
                'verbose_name': 'Mulk',
                'verbose_name_plural': 'Mulklar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Xarajat nomi')),
                ('category', models.CharField(choices=[('rent', 'Ijara'), ('internet', 'Internet'), ('advertising', 'Reklama'), ('equipment', 'Jihoz'), ('repair', "Ta'mirlash"), ('utilities', 'Kommunal'), ('salary', 'Ish haqi'), ('other', 'Boshqa')], db_index=True, default='other', max_length=20, verbose_name='Kategoriya')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Summa')),
                ('expense_date', models.DateField(db_index=True, verbose_name='Sana')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name="Kim qo'shdi")),
            ],
            options={
                'verbose_name': 'Xarajat',
                'verbose_name_plural': 'Xarajatlar',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Summa')),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "O'tkazma")], default='cash', max_length=10, verbose_name="To'lov turi")),
                ('receipt_number', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Chek raqami')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="To'lov vaqti")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.payment', verbose_name="To'lov hisobi")),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qildi')),
            ],
            options={
                'verbose_name': "To'lov operatsiyasi",
                'verbose_name_plural': "To'lov operatsiyalari",
                'ordering': ['-paid_at'],
            },
        ),
    ]
