# Generated by Django 5.0.6 on 2026-08-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='debt_after',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name="Shu to'lovdan keyingi qarz"),
        ),
    ]
