# Generated by Django 5.0.6 on 2026-08-18 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_asset_purchase_price'),
        ('groups', '0006_group_payment_due_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='groups.group', verbose_name='Guruh (tranzaksiya vaqtidagi)'),
        ),
    ]
