# Generated by Django 5.0.6 on 2026-09-22 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_paymenttransaction_group'),
        ('payments', '0004_alter_payment_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bekor qilish sababi'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bekor qilingan vaqt'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Kim bekor qildi'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='is_cancelled',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Bekor qilingan'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.payment', verbose_name="To'lov hisobi"),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "O'tkazma"), ('unknown', "Noma'lum (eski yozuv)")], default='cash', max_length=10, verbose_name="To'lov turi"),
        ),
    ]
