# Generated by Django 5.0.6 on 2026-09-22 10:35

from django.db import migrations, models

# Eski -> yangi (kelishilgan): "Karta" terminal orqali edi, "O'tkazma" kartadan o'tkazma edi
FORWARD = {'card': 'terminal', 'transfer': 'card_transfer'}
# Orqaga: ustun yana 10 belgiga qisqaradi, shuning uchun uzun kodlar eskisiga qaytariladi
BACKWARD = {'terminal': 'card', 'card_transfer': 'transfer', 'bank_account': 'transfer'}


def remap(mapping):
    def run(apps, schema_editor):
        PaymentTransaction = apps.get_model('finance', 'PaymentTransaction')
        for old, new in mapping.items():
            PaymentTransaction.objects.filter(payment_type=old).update(payment_type=new)
    return run


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_legacy_receipts_for_uncovered_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card_transfer', "Kartadan o'tkazma"), ('terminal', 'Terminal orqali'), ('bank_account', 'Hisob raqam orqali'), ('unknown', "Noma'lum (eski yozuv)")], default='cash', max_length=20, verbose_name="To'lov turi"),
        ),
        migrations.RunPython(remap(FORWARD), remap(BACKWARD)),
    ]
