# Generated by Django 5.0.6 on 2026-09-22 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_payment_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.asset', verbose_name='Markaz buyumi'),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Davomli (har oy)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Miqdor'),
        ),
        migrations.AddField(
            model_name='expense',
            name='recurring_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_copies', to='finance.expense', verbose_name="Qaysi xarajatdan ko'chirilgan"),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('rent', "Ijara to'lovi"), ('utilities', "Kommunal to'lov"), ('stationery', 'Kanselyariya'), ('purchase', 'Olib kelingan narsalar'), ('internet', 'Internet'), ('advertising', 'Reklama'), ('equipment', 'Jihoz'), ('repair', "Ta'mirlash"), ('salary', 'Ish haqi (eski)'), ('other', 'Boshqa')], db_index=True, default='other', max_length=20, verbose_name='Kategoriya'),
        ),
    ]
