# Generated by Django 5.0.6 on 2026-06-03 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlt_ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ailog',
            new_name='vlt_ai_ailo_user_id_b6606e_idx',
            old_name='vlt_ai_ailo_user_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='ailog',
            new_name='vlt_ai_ailo_tool_na_01a50c_idx',
            old_name='vlt_ai_ailo_tool_status_idx',
        ),
    ]
