# Generated by Django 5.0.6 on 2026-08-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlt_ai', '0002_rename_vlt_ai_ailo_user_id_status_idx_vlt_ai_ailo_user_id_b6606e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Taxminiy narx (USD)'),
        ),
        migrations.AddField(
            model_name='message',
            name='input_tokens',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kirish tokenlari'),
        ),
        migrations.AddField(
            model_name='message',
            name='model',
            field=models.CharField(blank=True, max_length=100, verbose_name='LLM modeli'),
        ),
        migrations.AddField(
            model_name='message',
            name='output_tokens',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Chiqish tokenlari'),
        ),
        migrations.AddField(
            model_name='message',
            name='request_status',
            field=models.CharField(choices=[('ok', 'Muvaffaqiyatli'), ('error', 'Xatolik'), ('ratelimit', 'Limit tugagan'), ('denied', 'Rad etilgan')], db_index=True, default='ok', max_length=10, verbose_name="So'rov holati"),
        ),
    ]
