# Generated by Django 5.0.6 on 2026-05-16 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('students', '0002_alter_student_options_student_parent_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='coins',
            field=models.PositiveIntegerField(default=0, verbose_name='Kumushlar'),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Daraja'),
        ),
        migrations.AddField(
            model_name='student',
            name='xp_points',
            field=models.PositiveIntegerField(default=0, verbose_name='XP Ball'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['-xp_points'], name='students_st_xp_poin_3a77a2_idx'),
        ),
    ]
