# Generated by Django 5.0.6 on 2026-05-30 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_parent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Telefon formati: +998901234567', regex='^\\+998\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Telefon formati: +998901234567', regex='^\\+998\\d{9}$')]),
        ),
    ]
