# Generated by Django 5.0.6 on 2026-09-22 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_parent_phone_alter_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='monthly_fee',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Shaxsiy oylik narx'),
        ),
    ]
