# Generated by Django 5.0.6 on 2026-09-22 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_copy_fee_from_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='monthly_fee',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Oylik to'lov"),
        ),
    ]
