# Generated by Django 5.0.6 on 2026-09-24 07:42

import django.core.validators
import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_rooms_from_schedules'),
        ('students', '0008_student_fee_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Oylik chegirma'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(check=models.Q(('discount__gte', 0), ('discount__lte', django.db.models.functions.comparison.Coalesce('monthly_fee', models.Value(0, output_field=models.DecimalField(decimal_places=0, max_digits=10))))), name='student_discount_within_fee'),
        ),
    ]
