# Generated by Django 5.0.6 on 2026-09-24 09:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0009_student_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150, verbose_name='Ism familiya otasining ismi')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Telefon')),
                ('address', models.CharField(max_length=300, verbose_name='Yashash manzili')),
                ('parent_name', models.CharField(max_length=150, verbose_name='Ota-ona ismi')),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(99)], verbose_name='Yosh')),
                ('direction', models.CharField(max_length=100, verbose_name="Yo'nalish")),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('contacted', "Bog'lanildi"), ('enrolled', 'Qabul qilindi'), ('rejected', 'Rad etildi')], db_index=True, default='new', max_length=10, verbose_name='Holat')),
                ('note', models.TextField(blank=True, verbose_name='Admin izohi')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='Qachon ishlangan')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_applications', to=settings.AUTH_USER_MODEL, verbose_name='Kim ishlagan')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='students.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='arizalar_ap_status_de29ce_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 3), ('age__lte', 99)), name='ariza_age_range'),
        ),
    ]
