# Generated by Django 5.0.6 on 2026-05-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='subject',
            field=models.CharField(blank=True, max_length=100, verbose_name="Fan / Yo'nalish"),
        ),
    ]
