# Generated by Django 5.0.6 on 2026-05-17 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('groups', '0002_backend_fixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='branches.branch', verbose_name='Filial'),
        ),
    ]
