# Generated by Django 5.0.6 on 2026-05-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_add_branch_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonschedule',
            name='room',
            field=models.CharField(blank=True, max_length=50, verbose_name='Xona'),
        ),
    ]
