# Generated by Django 5.0.6 on 2026-08-11 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_remove_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='payment_due_day',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name="To'lov muddati (oyning kuni)"),
        ),
    ]
