# Generated by Django 5.0.6 on 2026-09-22 10:49

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_remove_group_monthly_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Xona nomi')),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Sig'imi (o'rin)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xona',
                'verbose_name_plural': 'Xonalar',
                'ordering': ['name'],
            },
        ),
    ]
