# Generated by Django 5.0.6 on 2026-05-14 13:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.PositiveSmallIntegerField(verbose_name='Oy')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Yil')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name="To'lov summasi")),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name="To'langan summa")),
                ('debt_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Qarz summasi')),
                ('status', models.CharField(choices=[('paid', "To'langan"), ('partial', 'Qisman'), ('unpaid', "To'lanmagan")], default='unpaid', max_length=10, verbose_name='Holat')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name="To'lov sanasi")),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='groups.group', verbose_name='Guruh')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qilgan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-year', '-month'],
                'unique_together': {('student', 'group', 'month', 'year')},
            },
        ),
    ]
