# Generated by Django 5.0.6 on 2026-05-16 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('payments', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Chegirma'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('paid', "To'langan"), ('partial', 'Qisman'), ('unpaid', "To'lanmagan")], db_index=True, default='unpaid', max_length=10, verbose_name='Holat'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['month', 'year', 'status'], name='payments_pa_month_fc87a9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', 'year', 'month'], name='payments_pa_student_e77d34_idx'),
        ),
    ]
