# Generated by Django 5.0.6 on 2026-09-22 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_group_blank_true'),
        ('students', '0006_student_monthly_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='students.student', verbose_name="O'quvchi"),
        ),
    ]
