# Generated by Django 5.0.6 on 2026-08-13 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zukko', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='challengesubmission',
            constraint=models.UniqueConstraint(fields=('user', 'session', 'bugfind_challenge', 'coding_challenge'), name='unique_submission_per_user_session_challenge', nulls_distinct=False),
        ),
    ]
