# Generated by Django 5.0.6 on 2026-06-03 21:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceAuthLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('liveness_passed', models.BooleanField(null=True, verbose_name='Jonlilik')),
                ('identity_matched', models.BooleanField(null=True, verbose_name='Shaxsiyat')),
                ('result', models.CharField(choices=[('OK', 'Muvaffaqiyatli'), ('DENIED', 'Rad etildi')], max_length=10, verbose_name='Natija')),
                ('challenge', models.CharField(default='', max_length=50, verbose_name='Vazifa')),
                ('failure_reason', models.CharField(default='', max_length=250, verbose_name='Sabab')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_auth_logs', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Yuz autentifikatsiya jurnali',
                'verbose_name_plural': 'Yuz autentifikatsiya jurnallari',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FaceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_embedding', models.TextField(blank=True, null=True, verbose_name='Shifrlangan embedding')),
                ('status', models.CharField(choices=[('enrolled', "Ro'yxatdan o'tilgan"), ('not_enrolled', "Ro'yxatdan o'tilmagan")], default='not_enrolled', max_length=15, verbose_name='Holat')),
                ('enrolled_at', models.DateTimeField(blank=True, null=True, verbose_name="Ro'yxatga olingan sana")),
                ('consent_given', models.BooleanField(default=False, verbose_name='Rozilik berilgan')),
                ('consent_at', models.DateTimeField(blank=True, null=True, verbose_name='Rozilik sanasi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Yuz profili',
                'verbose_name_plural': 'Yuz profillari',
            },
        ),
    ]
