# Generated by Django 5.0.6 on 2026-08-13 14:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(db_index=True, max_length=64, unique=True)),
                ('error_type', models.CharField(max_length=200, verbose_name='Xatolik turi')),
                ('message', models.TextField(verbose_name='Sanitizatsiya qilingan xabar')),
                ('page', models.CharField(blank=True, max_length=300, verbose_name='Sahifa')),
                ('endpoint', models.CharField(blank=True, db_index=True, max_length=300, verbose_name='Endpoint')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='HTTP metod')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='HTTP status')),
                ('severity', models.CharField(choices=[('critical', 'Kritik'), ('high', 'Yuqori'), ('medium', "O'rta"), ('low', 'Past')], db_index=True, default='medium', max_length=10, verbose_name='Jiddiylik')),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('investigating', 'Tekshirilmoqda'), ('resolved', 'Hal qilindi'), ('ignored', "E'tiborsiz qoldirildi")], db_index=True, default='open', max_length=15, verbose_name='Holat')),
                ('occurrence_count', models.PositiveIntegerField(default=0, verbose_name='Takrorlanish soni')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name="Birinchi marta ko'ringan")),
                ('last_seen', models.DateTimeField(db_index=True, verbose_name="Oxirgi marta ko'ringan")),
                ('ai_analysis', models.JSONField(blank=True, null=True, verbose_name='AI tahlili')),
                ('ai_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_analyzed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_analyses_run', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xatolik guruhi',
                'verbose_name_plural': 'Xatolik guruhlari',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='ErrorOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_role', models.CharField(blank=True, max_length=20, verbose_name='Rol')),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=36, verbose_name="So'rov ID")),
                ('page', models.CharField(blank=True, max_length=300, verbose_name='Sahifa')),
                ('endpoint', models.CharField(blank=True, max_length=300, verbose_name='Endpoint')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='HTTP metod')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='HTTP status')),
                ('sanitized_message', models.TextField(blank=True, verbose_name='Xabar')),
                ('stack_trace', models.TextField(blank=True, verbose_name='Stack trace')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vaqt')),
                ('error_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='error_monitor.errorevent', verbose_name='Xatolik guruhi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_occurrences', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Xatolik holati',
                'verbose_name_plural': 'Xatolik holatlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='errorevent',
            index=models.Index(fields=['status', '-last_seen'], name='error_monit_status_e7edbd_idx'),
        ),
        migrations.AddIndex(
            model_name='errorevent',
            index=models.Index(fields=['severity', '-last_seen'], name='error_monit_severit_0fa740_idx'),
        ),
        migrations.AddIndex(
            model_name='erroroccurrence',
            index=models.Index(fields=['error_event', '-created_at'], name='error_monit_error_e_b43e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='erroroccurrence',
            index=models.Index(fields=['user', '-created_at'], name='error_monit_user_id_b7a228_idx'),
        ),
    ]
