# Generated by Django 5.0.6 on 2026-05-17 09:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('students', '0003_student_coins_student_level_student_xp_points_and_more'),
        ('teachers', '0002_teacher_photo_alter_teacher_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Topshiriq matni')),
                ('due_date', models.DateTimeField(db_index=True, verbose_name='Topshirish muddati')),
                ('max_score', models.PositiveSmallIntegerField(default=100, verbose_name='Maksimal ball')),
                ('xp_reward', models.PositiveSmallIntegerField(default=50, verbose_name='XP mukofot')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('active', 'Faol'), ('closed', 'Yopilgan')], db_index=True, default='active', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='homework/assignments/', verbose_name='Fayl (ixtiyoriy)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='groups.group', verbose_name='Guruh')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='teachers.teacher', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Vazifa',
                'verbose_name_plural': 'Vazifalar',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.TextField(blank=True, verbose_name='Javob matni')),
                ('file', models.FileField(blank=True, null=True, upload_to='homework/submissions/', verbose_name='Topshirilgan fayl')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ball')),
                ('feedback', models.TextField(blank=True, verbose_name="O'qituvchi izohi")),
                ('status', models.CharField(choices=[('submitted', 'Topshirildi'), ('graded', 'Baholandi'), ('late', 'Kech topshirildi'), ('missing', 'Topshirilmagan')], db_index=True, default='submitted', max_length=12)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework.assignment', verbose_name='Vazifa')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='students.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Topshiriq',
                'verbose_name_plural': 'Topshiriqlar',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status', 'group'], name='homework_as_status_2d5055_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['-created_at'], name='homework_as_created_e09af6_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'assignment'], name='homework_su_status_a08679_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', 'status'], name='homework_su_student_44ac56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('assignment', 'student')},
        ),
    ]
