# Generated by Django 5.0.6 on 2026-05-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assigned_date',
            field=models.DateField(blank=True, null=True, verbose_name='Berilgan sana'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='lesson_date',
            field=models.DateField(blank=True, null=True, verbose_name='Dars sanasi'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Tugash sanasi'),
        ),
    ]
