# Generated by Django 5.0.6 on 2026-06-01 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='file_content',
            field=models.BinaryField(blank=True, null=True, verbose_name='Fayl (binary)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fayl nomi'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='homework/assignments/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt', 'odt', 'jpg', 'jpeg', 'png', 'gif', 'ppt', 'pptx', 'xls', 'xlsx', 'csv', 'zip', 'rar', 'mp4', 'mp3'])], verbose_name='Fayl (ixtiyoriy)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='homework/submissions/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt', 'odt', 'jpg', 'jpeg', 'png', 'gif', 'ppt', 'pptx', 'xls', 'xlsx', 'csv', 'zip', 'rar', 'mp4', 'mp3'])], verbose_name='Topshirilgan fayl'),
        ),
    ]
