# Generated by Django 5.0.6 on 2026-08-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_submission_binary_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='kumush_awarded',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Berilgan Kumush'),
        ),
    ]
