# Generated by Django 5.0.6 on 2026-05-16 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/photos/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Format: +998901234567', regex='^\\+998\\d{9}$')]),
        ),
    ]
