# Generated by Django 5.0.6 on 2026-05-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_photo_alter_teacher_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(blank=True, max_length=100, verbose_name="Fan / Yo'nalish"),
        ),
    ]
