# Generated by Django 5.0.6 on 2026-05-21 14:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_add_branch_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSalaryPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.PositiveSmallIntegerField(verbose_name='Oy')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Yil')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name="To'langan summa")),
                ('bonus', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Bonus')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="To'lov sanasi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_payments_made', to=settings.AUTH_USER_MODEL, verbose_name="Kim to'ladi")),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='teachers.teacher', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': "Ish haqi to'lovi",
                'verbose_name_plural': "Ish haqi to'lovlari",
                'ordering': ['-year', '-month', '-paid_at'],
                'unique_together': {('teacher', 'month', 'year')},
            },
        ),
    ]
