# Generated by Django 5.0.6 on 2026-05-30 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_remove_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Telefon formati: +998901234567', regex='^\\+998\\d{9}$')]),
        ),
    ]
