# Generated by Django 5.0.6 on 2026-08-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_alter_teacher_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Soatlik stavka (hourly uchun)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='salary_type',
            field=models.CharField(choices=[('fixed', 'Oylik (belgilangan)'), ('hourly', 'Soatlik')], default='fixed', max_length=10, verbose_name='Maosh turi'),
        ),
        migrations.AddField(
            model_name='teachersalarypayment',
            name='deductions',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Ushlab qolingan summa'),
        ),
        migrations.AddField(
            model_name='teachersalarypayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'langan")], default='paid', max_length=10, verbose_name='Holat'),
        ),
        migrations.AddField(
            model_name='teachersalarypayment',
            name='worked_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Ishlagan soat'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Oylik maosh (fixed uchun)'),
        ),
        migrations.AlterField(
            model_name='teachersalarypayment',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Asosiy summa'),
        ),
    ]
