# Generated by Django 5.0.6 on 2026-09-22 15:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('grade_from', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)], verbose_name='Boshlanish sinfi')),
                ('grade_to', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)], verbose_name='Tugash sinfi')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', "E'lon qilingan"), ('registration_closed', "Ro'yxat yopilgan"), ('finished', 'Yakunlangan')], db_index=True, default='draft', max_length=20, verbose_name='Holati')),
                ('location', models.TextField(blank=True, verbose_name='Manzil')),
                ('registration_deadline', models.DateTimeField(verbose_name="Ro'yxatdan o'tish muddati")),
                ('competition_date', models.DateTimeField(blank=True, null=True, verbose_name='Musobaqa sanasi')),
                ('show_full_names', models.BooleanField(default=False, verbose_name="Natijalarda to'liq ism-familya")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_competitions', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan admin')),
            ],
            options={
                'verbose_name': 'Musobaqa',
                'verbose_name_plural': 'Musobaqalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=60, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=60, verbose_name='Familya')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Telefon formati: +998901234567', regex='^\\+998\\d{9}$')], verbose_name='Telefon')),
                ('address', models.TextField(verbose_name='Yashash manzili')),
                ('grade', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)], verbose_name='Sinf')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('confirmed', 'Tasdiqlandi')], db_index=True, default='new', max_length=10, verbose_name='Holati')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan vaqt")),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='musobaqalar.competition', verbose_name='Musobaqa')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_participants', to=settings.AUTH_USER_MODEL, verbose_name='Kim tasdiqladi')),
            ],
            options={
                'verbose_name': 'Ishtirokchi',
                'verbose_name_plural': 'Ishtirokchilar',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField(verbose_name='Ball')),
                ('place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="O'rin (sinf ichida)")),
                ('entered_at', models.DateTimeField(auto_now=True, verbose_name='Kiritilgan vaqt')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_results', to=settings.AUTH_USER_MODEL, verbose_name='Kim kiritdi')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='musobaqalar.participant', verbose_name='Ishtirokchi')),
            ],
            options={
                'verbose_name': 'Natija',
                'verbose_name_plural': 'Natijalar',
                'ordering': ['-score'],
            },
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(check=models.Q(('grade_from__lte', models.F('grade_to'))), name='competition_grade_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('status',), name='competition_single_published'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['competition', 'grade', 'status'], name='musobaqalar_competi_e734c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('competition', 'phone'), name='participant_unique_phone'),
        ),
    ]
