# Generated by Django 5.0.6 on 2026-09-22 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musobaqalar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)], verbose_name='Sinf'),
        ),
        migrations.AlterField(
            model_name='result',
            name='place',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="O'rin"),
        ),
    ]
