# Generated by Django 5.0.6 on 2026-05-21 13:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Yaratildi'), ('update', 'Yangilandi'), ('delete', "O'chirildi"), ('login', 'Tizimga kirdi'), ('logout', 'Tizimdan chiqdi')], db_index=True, max_length=10)),
                ('model_name', models.CharField(db_index=True, max_length=50, verbose_name='Model')),
                ('object_id', models.CharField(blank=True, max_length=50, verbose_name='Obyekt ID')),
                ('object_repr', models.CharField(max_length=200, verbose_name='Obyekt')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name="O'zgarishlar")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Faoliyat jurnali',
                'verbose_name_plural': 'Faoliyat jurnali',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='notifications.notification', verbose_name='Asl xabar'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('payment_reminder', "To'lov eslatmasi"), ('attendance_alert', 'Davomat ogohlantirishsi'), ('general', 'Umumiy'), ('support_message', 'Yordam xabari'), ('support_reply', 'Yordam javobi')], default='general', max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notif_type', 'sender'], name='notificatio_notif_t_c3d064_idx'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
