# Generated by Django 5.0.6 on 2026-08-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_activitylog_notification_parent_notification_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('create', 'Yaratildi'), ('update', 'Yangilandi'), ('delete', "O'chirildi"), ('login', 'Tizimga kirdi'), ('logout', 'Tizimdan chiqdi'), ('denied', 'Rad etildi'), ('ratelimit', 'Limit tugadi')], db_index=True, max_length=10),
        ),
    ]
